# Generated by Django 4.0.2 on 2022-02-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(null=True, upload_to='about/', verbose_name='Banner')),
                ('title', models.CharField(max_length=2000, verbose_name='About title ')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': '2.0 О Компании',
                'verbose_name_plural': '2.0 О Компании',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Slider name')),
                ('content', models.TextField(verbose_name='Slider description')),
                ('image', models.ImageField(upload_to='banner/', verbose_name='Main image')),
            ],
            options={
                'verbose_name': '1.0 Баннер',
                'verbose_name_plural': '1.0 Баннер',
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company_name')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Phone_number')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': '5.1 Контактная форма',
                'verbose_name_plural': '5.1 Контактная форма',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=200, verbose_name='Phone number2 ')),
                ('email', models.CharField(max_length=200, verbose_name='Email ')),
                ('address', models.CharField(max_length=200, verbose_name='Address ')),
                ('telegram', models.CharField(max_length=200, verbose_name='Telegram ')),
                ('youtube', models.CharField(max_length=200, verbose_name='Youtube')),
                ('instagram', models.CharField(max_length=200, verbose_name='Instagram ')),
                ('facebook', models.CharField(max_length=200, verbose_name='Facebook')),
            ],
            options={
                'verbose_name': '5.0 Контакты',
                'verbose_name_plural': '5.0 Контакты',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(null=True, upload_to='about/', verbose_name='Banner')),
                ('title', models.CharField(max_length=2000, verbose_name='Service Title ')),
                ('description', models.TextField(verbose_name='Text')),
            ],
            options={
                'verbose_name': '3.0 О Сервисы',
                'verbose_name_plural': '3.0 О Сервисы',
            },
        ),
        migrations.CreateModel(
            name='Trust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(null=True, upload_to='logo/', verbose_name='Company logo')),
            ],
            options={
                'verbose_name': '4.0 Нам доверяют',
                'verbose_name_plural': '4.0 Нам доверяют',
            },
        ),
    ]
