# Generated by Django 4.0.2 on 2022-02-19 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Slider name')),
                ('content', models.TextField(verbose_name='Slider description')),
                ('image', models.ImageField(upload_to='banner/', verbose_name='Main image')),
            ],
            options={
                'verbose_name': '3.0 Документы',
                'verbose_name_plural': '3.0 Документы',
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serv', to='uzimpex.services'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='document',
            field=models.FileField(null=True, upload_to='document/'),
        ),
    ]
