# Generated by Django 4.0.2 on 2022-02-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0002_documents_banner_services_contacts_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(null=True, upload_to='about/', verbose_name='Banner')),
                ('title', models.CharField(max_length=2000, verbose_name='About title ')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': '2.0 О Тариф',
                'verbose_name_plural': '2.0 О Тариф',
            },
        ),
    ]
