# Generated by Django 4.0.3 on 2023-12-07 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0002_alter_contactform_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 7, 18, 12, 58, 241739), null=True, verbose_name='Получено'),
        ),
    ]
