# Generated by Django 4.0.2 on 2022-02-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0004_services_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='image',
        ),
        migrations.AddField(
            model_name='documents',
            name='file',
            field=models.FileField(null=True, upload_to='documents/', verbose_name='Main image'),
        ),
    ]
