# Generated by Django 4.0.2 on 2022-02-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0005_remove_documents_image_documents_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': '7.1 Контактная форма', 'verbose_name_plural': '7.1 Контактная форма'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': '7.0 Контакты', 'verbose_name_plural': '7.0 Контакты'},
        ),
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name': '6.0 Документы', 'verbose_name_plural': '6.0 Документы'},
        ),
        migrations.AlterModelOptions(
            name='plans',
            options={'verbose_name': '5.0 О Тариф', 'verbose_name_plural': '5.0 О Тариф'},
        ),
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name='Main image'),
        ),
    ]
