# Generated by Django 4.0.2 on 2022-02-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0007_remove_contactform_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Получено'),
        ),
    ]
