# Generated by Django 4.0.2 on 2022-02-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0008_contactform_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='document',
            field=models.FileField(null=True, upload_to='', verbose_name='Main image'),
        ),
    ]
