# Generated by Django 4.0.2 on 2022-02-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0009_alter_contacts_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='small_banner',
            field=models.ImageField(null=True, upload_to='about/', verbose_name='Banner2'),
        ),
    ]
