# Generated by Django 4.0.2 on 2022-02-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0010_about_description2_about_small_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_other',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_photo',
            field=models.TextField(blank=True),
        ),
    ]
