# Generated by Django 4.0.2 on 2022-02-21 04:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0011_about_description_other_about_description_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='description2',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='description_other',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='description_photo',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Slider description'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, null=True, verbose_name='Получено'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Slider description'),
        ),
        migrations.AlterField(
            model_name='plans',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Text'),
        ),
    ]
