# Generated by Django 4.0.2 on 2022-03-18 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0012_alter_about_description_alter_about_description2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='small_banner',
            new_name='banner_image1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='about',
            name='description_other',
        ),
        migrations.RemoveField(
            model_name='about',
            name='description_photo',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 3, 18, 10, 57, 0, 724596), null=True, verbose_name='Получено'),
        ),
    ]
