# Generated by Django 4.0.2 on 2022-03-18 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0014_remove_plans_banner_plans_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='type',
            field=models.CharField(choices=[('GOLD', 'GOLD'), ('SILVER', 'SILVER'), ('SIMPLE', 'SIMPLE')], max_length=200, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 3, 18, 11, 16, 49, 501378), null=True, verbose_name='Получено'),
        ),
    ]
