# Generated by Django 4.0.2 on 2022-03-18 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0015_plans_type_alter_contactform_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 3, 18, 15, 20, 49, 962147), null=True, verbose_name='Получено'),
        ),
        migrations.AlterField(
            model_name='plans',
            name='type',
            field=models.CharField(choices=[('GOLD', 'GOLD'), ('PREMIUM', 'PREMIUM'), ('FREE', 'FREE')], max_length=200, null=True, verbose_name='Type'),
        ),
    ]
