# Generated by Django 4.0.2 on 2022-03-19 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0016_alter_contactform_data_alter_plans_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='banner_image2',
            field=models.ImageField(null=True, upload_to='about/', verbose_name='Banner2'),
        ),
        migrations.AlterField(
            model_name='about',
            name='banner_image1',
            field=models.ImageField(null=True, upload_to='about/', verbose_name='Banner1'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 3, 19, 17, 18, 43, 691020), null=True, verbose_name='Получено'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Slider name'),
        ),
    ]
