# Generated by Django 4.0.3 on 2022-03-20 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0017_about_banner_image2_alter_about_banner_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 3, 20, 10, 37, 26, 134771), null=True, verbose_name='Получено'),
        ),
    ]
