# Generated by Django 4.0.3 on 2022-04-01 01:42

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0024_alter_contactform_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obnova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': '2.4 Обновления',
                'verbose_name_plural': '2.4 Обновления',
            },
        ),
        migrations.CreateModel(
            name='Otdeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': '2.2 Отделы',
                'verbose_name_plural': '2.2 Отделы',
            },
        ),
        migrations.CreateModel(
            name='Ruk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': '2.1 Руководство',
                'verbose_name_plural': '2.1 Руководство',
            },
        ),
        migrations.CreateModel(
            name='Vacansiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': '2.3 Вакансии',
                'verbose_name_plural': '2.3 Вакансии',
            },
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 4, 1, 6, 42, 39, 932744), null=True, verbose_name='Получено'),
        ),
    ]
