# Generated by Django 4.0.2 on 2022-04-06 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0026_alter_obnova_options_alter_contactform_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 4, 6, 14, 29, 0, 501976), null=True, verbose_name='Получено'),
        ),
    ]
