# Generated by Django 4.0.2 on 2022-04-06 12:32

import ckeditor.fields
import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0027_alter_contactform_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description2_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description2_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(max_length=2000, null=True, verbose_name='About title '),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.CharField(max_length=2000, null=True, verbose_name='About title '),
        ),
        migrations.AddField(
            model_name='banner',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Slider description'),
        ),
        migrations.AddField(
            model_name='banner',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Slider description'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Slider name'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Slider name'),
        ),
        migrations.AddField(
            model_name='documents',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Slider description'),
        ),
        migrations.AddField(
            model_name='documents',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Slider description'),
        ),
        migrations.AddField(
            model_name='documents',
            name='title_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Slider name'),
        ),
        migrations.AddField(
            model_name='documents',
            name='title_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Slider name'),
        ),
        migrations.AddField(
            model_name='obnova',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='obnova',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='otdeli',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='otdeli',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='title_en',
            field=models.CharField(max_length=2000, null=True, verbose_name='About title '),
        ),
        migrations.AddField(
            model_name='plans',
            name='title_ru',
            field=models.CharField(max_length=2000, null=True, verbose_name='About title '),
        ),
        migrations.AddField(
            model_name='ruk',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='ruk',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='services',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='services',
            name='title_en',
            field=models.CharField(max_length=2000, null=True, verbose_name='Service Title '),
        ),
        migrations.AddField(
            model_name='services',
            name='title_ru',
            field=models.CharField(max_length=2000, null=True, verbose_name='Service Title '),
        ),
        migrations.AddField(
            model_name='vacansiya',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='vacansiya',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 4, 6, 17, 32, 3, 789465), null=True, verbose_name='Получено'),
        ),
    ]
