# Generated by Django 4.0.3 on 2022-04-07 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0030_contacts_address_ru_contacts_address_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 4, 7, 16, 56, 43, 199157), null=True, verbose_name='Получено'),
        ),
    ]
