# Generated by Django 4.0.3 on 2022-04-07 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0031_alter_contactform_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 4, 7, 17, 26, 20, 138173), null=True, verbose_name='Получено'),
        ),
    ]
