# Generated by Django 4.0.3 on 2022-05-31 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0033_alter_contactform_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obnova',
            options={'verbose_name': '2.3 Новости', 'verbose_name_plural': '2.3 Новости'},
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 5, 31, 9, 51, 31, 744640), null=True, verbose_name='Получено'),
        ),
    ]
