# Generated by Django 4.0.3 on 2022-05-31 05:17

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0035_alter_contactform_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='obnova',
            name='image',
            field=models.ImageField(null=True, upload_to='about/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='obnova',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='obnova',
            name='title',
            field=models.CharField(max_length=2000, null=True, verbose_name='News title'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 5, 31, 10, 17, 55, 310150), null=True, verbose_name='Получено'),
        ),
        migrations.AlterField(
            model_name='obnova',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='obnova',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='obnova',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Text'),
        ),
    ]
