# Generated by Django 4.0.3 on 2022-07-13 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0037_obnova_title_ru_obnova_title_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obnova',
            name='image1',
            field=models.ImageField(null=True, upload_to='about/', verbose_name='Image1'),
        ),
        migrations.AddField(
            model_name='obnova',
            name='image2',
            field=models.ImageField(null=True, upload_to='about/', verbose_name='Image2'),
        ),
        migrations.AddField(
            model_name='obnova',
            name='image3',
            field=models.ImageField(null=True, upload_to='about/', verbose_name='Image3'),
        ),
        migrations.AddField(
            model_name='obnova',
            name='image4',
            field=models.ImageField(null=True, upload_to='about/', verbose_name='Image4'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 7, 13, 17, 29, 50, 122398), null=True, verbose_name='Получено'),
        ),
    ]
