# Generated by Django 4.0.3 on 2022-07-14 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0038_obnova_image1_obnova_image2_obnova_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='banner1',
            field=models.ImageField(null=True, upload_to='about/', verbose_name='Banner1'),
        ),
        migrations.AddField(
            model_name='services',
            name='banner2',
            field=models.ImageField(null=True, upload_to='about/', verbose_name='Banner2'),
        ),
        migrations.AddField(
            model_name='services',
            name='banner3',
            field=models.ImageField(null=True, upload_to='about/', verbose_name='Banner3'),
        ),
        migrations.AddField(
            model_name='services',
            name='banner4',
            field=models.ImageField(null=True, upload_to='about/', verbose_name='Banner4'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 7, 14, 11, 8, 31, 904778), null=True, verbose_name='Получено'),
        ),
    ]
