# Generated by Django 4.0.3 on 2022-07-14 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0039_services_banner1_services_banner2_services_banner3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 7, 14, 11, 56, 19, 970318), null=True, verbose_name='Получено'),
        ),
        migrations.AlterField(
            model_name='obnova',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='obnova',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Image1'),
        ),
        migrations.AlterField(
            model_name='obnova',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Image2'),
        ),
        migrations.AlterField(
            model_name='obnova',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Image3'),
        ),
        migrations.AlterField(
            model_name='obnova',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Image4'),
        ),
        migrations.AlterField(
            model_name='services',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='services',
            name='banner1',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Banner1'),
        ),
        migrations.AlterField(
            model_name='services',
            name='banner2',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Banner2'),
        ),
        migrations.AlterField(
            model_name='services',
            name='banner3',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Banner3'),
        ),
        migrations.AlterField(
            model_name='services',
            name='banner4',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Banner4'),
        ),
    ]
