# Generated by Django 5.0 on 2023-12-15 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0044_alter_contactform_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='logo/', verbose_name='Useful links')),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 15, 18, 21, 49, 999770), null=True, verbose_name='Получено'),
        ),
    ]
