# Generated by Django 5.0 on 2023-12-15 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0045_usefullink_alter_contactform_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsefulLink',
            new_name='UsefulLinks',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 15, 18, 22, 42, 927597), null=True, verbose_name='Получено'),
        ),
    ]
