# Generated by Django 5.0 on 2023-12-15 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0046_rename_usefullink_usefullinks_alter_contactform_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='usefullinks',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 15, 18, 24, 31, 558666), null=True, verbose_name='Получено'),
        ),
    ]
