# Generated by Django 4.0.3 on 2023-12-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0004_usefullinks_trust_link_trust_name_and_more'),
        ('uzimpex', '0047_usefullinks_name_alter_contactform_data'),
    ]

    operations = [
    ]
