# Generated by Django 4.0.3 on 2023-12-22 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0047_usefullinks_name_alter_contactform_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(null=True, upload_to='logo/', verbose_name='Useful links')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': '7.3 Полезные ссылки',
                'verbose_name_plural': '7.3 Полезные ссылки',
            },
        ),
        migrations.AlterModelOptions(
            name='usefullinks',
            options={'verbose_name': '7.2 Партнёры', 'verbose_name_plural': '7.2 Партнёры'},
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 22, 16, 30, 42, 896139), null=True, verbose_name='Получено'),
        ),
    ]
