# Generated by Django 4.0.3 on 2023-12-22 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0048_merge_20231222_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usefullinks',
            options={'verbose_name': '7.2 Партнёры', 'verbose_name_plural': '7.2 Партнёры'},
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 22, 16, 19, 51, 985527), null=True, verbose_name='Получено'),
        ),
    ]
