# Generated by Django 4.0.3 on 2023-12-22 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0048_links_alter_usefullinks_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 22, 17, 24, 56, 173128), null=True, verbose_name='Получено'),
        ),
    ]
