# Generated by Django 4.0.3 on 2022-01-19 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0049_alter_contactform_data'),
        ('uzimpex', '0049_alter_usefullinks_options_alter_contactform_data'),
        ('uzimpex', '0050_alter_usefullinks_options_alter_contactform_data'),
    ]

    operations = [
    ]
