# Generated by Django 4.0.3 on 2022-04-03 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0052_projects_alter_contactform_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Home Video', max_length=128)),
                ('video_uz', models.FileField(blank=True, null=True, upload_to='static/home_video/videos')),
                ('video_ru', models.FileField(blank=True, null=True, upload_to='static/home_video/videos')),
                ('video_en', models.FileField(blank=True, null=True, upload_to='static/home_video/videos')),
            ],
            options={
                'verbose_name': '7.5 Видео',
                'verbose_name_plural': '7.5 Видео',
            },
        ),
        migrations.AddField(
            model_name='projects',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='title_en',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='title_ru',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='title_uz',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 4, 3, 6, 46, 46, 520977), null=True, verbose_name='Получено'),
        ),
    ]
