# Generated by Django 4.0.3 on 2022-04-03 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0053_homevideo_projects_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 4, 3, 6, 53, 28, 209073), null=True, verbose_name='Получено'),
        ),
        migrations.AlterField(
            model_name='homevideo',
            name='video_en',
            field=models.FileField(blank=True, null=True, upload_to='home_video/videos'),
        ),
        migrations.AlterField(
            model_name='homevideo',
            name='video_ru',
            field=models.FileField(blank=True, null=True, upload_to='home_video/videos'),
        ),
        migrations.AlterField(
            model_name='homevideo',
            name='video_uz',
            field=models.FileField(blank=True, null=True, upload_to='home_video/videos'),
        ),
    ]
