# Generated by Django 5.0.8 on 2022-09-16 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0055_alter_contactform_data_alter_homevideo_video_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='youtube',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 9, 17, 0, 56, 55, 208801), null=True, verbose_name='Получено'),
        ),
    ]
