# Generated by Django 5.0.8 on 2022-09-16 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0056_remove_contacts_facebook_remove_contacts_youtube_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 9, 17, 1, 6, 56, 33125), null=True, verbose_name='Получено'),
        ),
    ]
