# Generated by Django 5.0.8 on 2022-09-16 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0061_contacts_facebook_alter_contactform_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plans',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 9, 17, 1, 19, 5, 481469), null=True, verbose_name='Получено'),
        ),
    ]
