# Generated by Django 5.0.8 on 2022-09-16 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0062_delete_plans_alter_contactform_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 9, 17, 1, 22, 13, 749855), null=True, verbose_name='Получено'),
        ),
    ]
