# Generated by Django 5.0.9 on 2022-09-17 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0064_alter_contactform_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='facebook',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 9, 17, 5, 14, 42, 736053), null=True, verbose_name='Получено'),
        ),
    ]
