# Generated by Django 5.0.8 on 2022-09-28 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0067_remove_banner_content_remove_banner_content_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Obnova',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 9, 29, 2, 50, 25, 705208), null=True, verbose_name='Получено'),
        ),
    ]
