# Generated by Django 5.0.8 on 2022-09-28 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0068_delete_obnova_alter_contactform_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trust',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 9, 29, 2, 54, 32, 292905), null=True, verbose_name='Получено'),
        ),
    ]
