# Generated by Django 5.0.8 on 2022-09-28 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0069_delete_trust_alter_contactform_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='content',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='content_uz',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 9, 29, 4, 35, 40, 260340), null=True, verbose_name='Получено'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name='Main file'),
        ),
    ]
