# Generated by Django 5.0.8 on 2022-09-28 23:41

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0070_remove_documents_content_remove_documents_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='exit', verbose_name='Slider description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Slider description'),
        ),
        migrations.AddField(
            model_name='documents',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Slider description'),
        ),
        migrations.AddField(
            model_name='documents',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Slider description'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 9, 29, 4, 41, 32, 511021), null=True, verbose_name='Получено'),
        ),
    ]
