# Generated by Django 5.0.9 on 2024-10-01 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0075_remove_contacts_document_alter_contactform_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homevideo',
            old_name='video_en',
            new_name='video',
        ),
        migrations.RemoveField(
            model_name='homevideo',
            name='video_ru',
        ),
        migrations.RemoveField(
            model_name='homevideo',
            name='video_uz',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 10, 2, 1, 30, 25, 88445), null=True, verbose_name='Получено'),
        ),
    ]
