# Generated by Django 5.0.9 on 2024-10-01 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0076_rename_video_en_homevideo_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 10, 2, 2, 42, 41, 921007), null=True, verbose_name='Получено'),
        ),
    ]
