# Generated by Django 5.0.9 on 2024-10-01 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0077_alter_contactform_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacansiya',
        ),
        migrations.RemoveField(
            model_name='homevideo',
            name='video',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 10, 2, 4, 0, 7, 350409), null=True, verbose_name='Получено'),
        ),
    ]
