# Generated by Django 5.0.9 on 2024-10-01 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0078_delete_vacansiya_remove_homevideo_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homevideo',
            name='video_uz',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 10, 2, 4, 0, 59, 796573), null=True, verbose_name='Получено'),
        ),
    ]
