# Generated by Django 5.0.9 on 2024-10-02 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0080_rename_video_uz_homevideo_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 10, 3, 1, 33, 3, 914038), null=True, verbose_name='Получено'),
        ),
    ]
