# Generated by Django 5.0.9 on 2024-10-03 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0083_alter_contactform_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 10, 4, 1, 54, 32, 44267), null=True, verbose_name='Получено'),
        ),
    ]
