# Generated by Django 5.0.9 on 2024-10-05 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzimpex', '0084_alter_contactform_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 10, 6, 1, 32, 36, 203436), null=True, verbose_name='Получено'),
        ),
    ]
